arch:
  - amd64
  - ppc64le
  - s390x
  
dist: focal
 
script:
  - sudo apt update -y
  - sudo apt install wget -y
  - sudo cat /etc/resolv.conf
  #- curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  - wget -O /dev/null -q --show-progress http://speedtest.wdc01.softlayer.com/downloads/test500.zip

