arch:
  - amd64
  - ppc64le
  - s390x
  
dist: focal
 
script:
  - sudo cat /etc/resolv.conf
  - curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  - wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip
